### ISSUE TITLE
Watermark/stamp control

### ISSUE THREAD

**Issue by art2crazy** [hhrutter/pdfcpu#62]
Hi Horst,

I've been playing around with your library and in particular, the stamp/watermark feature - in addition to issue [#61](https://github.com/hhrutter/pdfcpu/issues/61) (thank you for adding it to your list of enhancements btw.) there are few things that I'm hoping you'd consider adding/changing.

One issue with using watermark/stamp is that when pdf has images in it, watermark being on the bottom, will be covered by them; on the other hand stamp is not transparent, and I don't see a way to set it. So, would you consider adding ability/some more controls to the stamp - alpha, angle, size maybe position?

Or, different option, and this is what I do right now as a workaround - in gofpdf I create a separate file with multi-line text, alpha, etc. and use it as a stamp; however, since pdfcpu does its own rotation, scaling and placement, I have to use custom page size, rotate -90 and move text around, to achieve my desired effect (large transparent text positioned in the upper part of the document, rotated -45 degrees - those are my project requirements). Right now the settings I have in gofpdf are basically trial and error based on a fixed text. It would be much easier to create a file in gofpdf with final rotation, alpha, size & position, and then instruct pdfcpu to just use it as stamp without any additional processing. This would put the burden of providing "proper" stamp file on the user.
Maybe expanding Watermark with an option "noprocess bool" (default false) and adding new function (similar to ParseWatermarkDetails) ParseWatermarkNoProcess that will set noprocess to true... this is more of me thinking at loud than a proposal, but I'm hoping this would be nice addition to your already great library. 

art

**Comment by hhrutter** [comment]
Thanks for using pdfcpu.

First of all I have to apologize for the lack of documentation but this will be my main focus now.
Meanwhile I recommend using `stamp` over `watermark` and I am thinking of getting rid of `watermark`completely. This is because more than often watermarks get covered by content or disappear. (Playing around with opacity can turn any stamp into a watermark. See below).

But pdfcpu has got you covered. There is a way to set a couple of parameters via the description string like so that may help you in this scenario:

`pdfcpu stamp 'Intentionally left blank, s:.75 abs, p:48, o:.5'` where o is the value for opacity between 0 and 1.

`pdfcpu help stamp` is your friend.

As far as positioning I agree with you.
`pdfcpu import` uses 9 anchors for positioning and an offset value.
My plan is to also incorporate positioning into stamping.

Have fun!
💚

**Comment by art2crazy** [comment]
> pdfcpu stamp 'Intentionally left blank, s:.75 abs, p:48, o:.5'

This is perfect, thank you so much! 

Closing this issue.
art
