### ISSUE TITLE
Extracting text with a specific font with a rectangular region as selection area

### ISSUE THREAD

**Issue by kskyten** [hhrutter/pdfcpu#78]
It is common to use different fonts to denote semantic meaning (e.g italics for emphasis or larger font size for section titles). Is it possible to extract text that is in a specific font and size? Also, is it possible to specify a region where to extract from? I would like to be able to, for example, extract all the italic text inside a region.

**Comment by hhrutter** [comment]
Extracting text from PDF is not trivial and currently not supported. See also #4.

Besides, if you wanted to extract text based on the font size that's something you can't really do easily as well, because a text matrix and the current transform matrix may change the subjective font size once the PDF page is rendered.
