### ISSUE TITLE
Error opening PDF file: previous xref stream not allowed

### ISSUE THREAD

**Issue by jim** [hhrutter/pdfcpu#90]
We're using pdfcpu to merge PDF files uploaded by users together. We are encountering an issue with a certain PDF file when we attempt to merge it with other PDFs [in this code](https://github.com/transcom/mymove/blob/master/pkg/paperwork/generator.go#L250).

I am able to get the same error using the `pdfcpu` command line to validate the file in question. so I think it has to do with reading in the file generally:

```console
$ pdfcpu validate testdata/orders.pdf 
validating(mode=relaxed) testdata/orders.pdf ...
Read failed.: xRefTable failed: parseHybridXRefStream: previous xref stream not allowed
```

I don't know the origins of this particular PDF and don't doubt that it is invalid according to the spec, but since these files are user-uploaded files we don't have control over how they are generated.

[Here is the problem file](https://github.com/hhrutter/pdfcpu/files/3327235/xrefheader_error.pdf).

I don't know enough about the PDF format to say if this is something that pdfcpu should be able to cope with or not.

**Comment by hhrutter** [comment]
Thanks for reporting this!
We don't actually care about any previous xref stream for hybrid PDFs.
Your file discovered another issue.
It's encrypted actually with V=2 (RC4) and that was not supported either because for one RC4 is old and
secondly not recommended anymore these days. 
Fixed in upcoming release.
